import { ICargo } from "../models/cargo.interface";

export const DataCargos: ICargo[] = [
    {IdCargo:1, Descripcion_esp:'Adjunto Gerencia de Producción', Descripcion_eng: 'Assistant Production Manager'},
    {IdCargo:2, Descripcion_esp:'Adjunto Gerencia General', Descripcion_eng: 'Deputy General Manager'},
    {IdCargo:3, Descripcion_esp:'Administración y Finanzas', Descripcion_eng: 'Administration and Finance'},
    {IdCargo:4, Descripcion_esp:'Administrador', Descripcion_eng: 'Administrator'},
    {IdCargo:5, Descripcion_esp:'Administrador Comercial', Descripcion_eng: 'Commercial Administrator'},
    {IdCargo:6, Descripcion_esp:'Administrador de Línea', Descripcion_eng: 'Line Administrator'},
    {IdCargo:7, Descripcion_esp:'Administrador General', Descripcion_eng: 'General Administrator'},
    {IdCargo:8, Descripcion_esp:'Admisión', Descripcion_eng: 'Admission'},
    {IdCargo:9, Descripcion_esp:'Agente Comercial', Descripcion_eng: 'Commercial Agent'},
    {IdCargo:10, Descripcion_esp:'Agregado Comercial', Descripcion_eng: 'Commercial Attache'},
    {IdCargo:11, Descripcion_esp:'Alcalde Distrital', Descripcion_eng: 'District Mayor'},
    {IdCargo:12, Descripcion_esp:'Alcalde Provincial', Descripcion_eng: 'Provincial Mayor'},
    {IdCargo:13, Descripcion_esp:'Analista', Descripcion_eng: 'Analyst'},
    {IdCargo:14, Descripcion_esp:'Analista de Calidad', Descripcion_eng: 'Quality Analyst'},
    {IdCargo:15, Descripcion_esp:'Analista de Comercio Exterior', Descripcion_eng: 'Analyst Foreign Trade'},
    {IdCargo:16, Descripcion_esp:'Analista de Compras', Descripcion_eng: 'Purchasing Analyst'},
    {IdCargo:17, Descripcion_esp:'Analista de Costos', Descripcion_eng: 'Cost Analyst'},
    {IdCargo:18, Descripcion_esp:'Analista de Desarrollo', Descripcion_eng: 'Development Analyst'},
    {IdCargo:19, Descripcion_esp:'Analista de Exportaciones', Descripcion_eng: 'Analyst Exports'},
    {IdCargo:20, Descripcion_esp:'Analista de Ingeniería', Descripcion_eng: 'Engineering Analyst'},
    {IdCargo:21, Descripcion_esp:'Analista de Logística', Descripcion_eng: 'Logistics Analyst'},
    {IdCargo:22, Descripcion_esp:'Analista de Marketing', Descripcion_eng: 'Marketing Analyst'},
    {IdCargo:23, Descripcion_esp:'Analista de Negocios', Descripcion_eng: 'Business Analyst'},
    {IdCargo:24, Descripcion_esp:'Analista de Prenda', Descripcion_eng: 'Analyst Pledge'},
    {IdCargo:25, Descripcion_esp:'Analista de Producto', Descripcion_eng: 'Analyst Product'},
    {IdCargo:26, Descripcion_esp:'Analista de Recursos Humanos', Descripcion_eng: 'Human Resources Analyst'},
    {IdCargo:27, Descripcion_esp:'Analista en Desarrollo', Descripcion_eng: 'Development Analyst'},
    {IdCargo:28, Descripcion_esp:'Analista Ferias Internacionales', Descripcion_eng: 'Analyst International Fairs'},
    {IdCargo:29, Descripcion_esp:'Analista Financiero', Descripcion_eng: 'Financial Analyst'},
    {IdCargo:30, Descripcion_esp:'Analista Textil', Descripcion_eng: 'Textile Analyst'},
    {IdCargo:31, Descripcion_esp:'Apoderado', Descripcion_eng: 'Agent'},
    {IdCargo:32, Descripcion_esp:'Area Comercial', Descripcion_eng: 'Commercial Area'},
    {IdCargo:33, Descripcion_esp:'Area de Desarrollo', Descripcion_eng: 'Development area'},
    {IdCargo:34, Descripcion_esp:'Area de Pigmentos y Textiles', Descripcion_eng: 'Pigments and Textile Area'},
    {IdCargo:35, Descripcion_esp:'Area de Plásticos', Descripcion_eng: 'Plastics Area'},
    {IdCargo:36, Descripcion_esp:'Area Textil', Descripcion_eng: 'Textile Area'},
    {IdCargo:37, Descripcion_esp:'Arquitectura Ferial', Descripcion_eng: 'Architecture Exhibition'},
    {IdCargo:38, Descripcion_esp:'Asesor', Descripcion_eng: 'Advisor'},
    {IdCargo:39, Descripcion_esp:'Asesor Administrativo', Descripcion_eng: 'Administrative Advisor'},
    {IdCargo:40, Descripcion_esp:'Asesor Comercial', Descripcion_eng: 'Commercial Advisor'},
    {IdCargo:41, Descripcion_esp:'Asesor Corporativo', Descripcion_eng: 'Corporate Advisory'},
    {IdCargo:42, Descripcion_esp:'Asesor de Comercio Exterior', Descripcion_eng: 'Foreing Trade Advisor'},
    {IdCargo:43, Descripcion_esp:'Asesor de Negocios', Descripcion_eng: 'Business advisor'},
    {IdCargo:44, Descripcion_esp:'Asesor de Ventas', Descripcion_eng: 'Sales Advisor'},
    {IdCargo:45, Descripcion_esp:'Asesor Financiero', Descripcion_eng: 'Investment Advisor'},
    {IdCargo:46, Descripcion_esp:'Asesor Legal', Descripcion_eng: 'Counselor'},
    {IdCargo:47, Descripcion_esp:'Asesor Técnico', Descripcion_eng: 'Technical Advisor'},
    {IdCargo:48, Descripcion_esp:'Asesoría de Lavandería', Descripcion_eng: 'Laundry Consulting'},
    {IdCargo:49, Descripcion_esp:'Asistente', Descripcion_eng: 'Assitant'},
    {IdCargo:50, Descripcion_esp:'Asistente Administrativo', Descripcion_eng: 'Administrative assistant'},
    {IdCargo:51, Descripcion_esp:'Asistente Comercial', Descripcion_eng: 'Commercial Assistant'},
    {IdCargo:52, Descripcion_esp:'Asistente de Abastecimientos', Descripcion_eng: 'Assistant Supply'},
    {IdCargo:53, Descripcion_esp:'Asistente de Administración', Descripcion_eng: 'Administrative Assistant'},
    {IdCargo:54, Descripcion_esp:'Asistente de Almacén', Descripcion_eng: 'Warehouse Assistant'},
    {IdCargo:55, Descripcion_esp:'Asistente de Comercio Exterior', Descripcion_eng: 'Foreing Trade Assitant'},
    {IdCargo:56, Descripcion_esp:'Asistente de Compras', Descripcion_eng: 'Purchasing Assistant'},
    {IdCargo:57, Descripcion_esp:'Asistente de Contabilidad', Descripcion_eng: 'Accounting Assistant'},
    {IdCargo:58, Descripcion_esp:'Asistente de Diseño', Descripcion_eng: 'Design assistant'},
    {IdCargo:59, Descripcion_esp:'Asistente de Exportaciones', Descripcion_eng: 'Export Assistant'},
    {IdCargo:60, Descripcion_esp:'Asistente de Gerencia', Descripcion_eng: 'Management Assistant'},
    {IdCargo:61, Descripcion_esp:'Asistente de Hilados', Descripcion_eng: 'Yarn Assistant'},
    {IdCargo:62, Descripcion_esp:'Asistente de Importaciones', Descripcion_eng: 'Import Wizard'},
    {IdCargo:63, Descripcion_esp:'Asistente de Ingenieria', Descripcion_eng: 'Engineering Assistant'},
    {IdCargo:64, Descripcion_esp:'Asistente de Laboratorio', Descripcion_eng: 'Laboratory Assistant'},
    {IdCargo:65, Descripcion_esp:'Asistente de Logística', Descripcion_eng: 'Logistics Assistant'},
    {IdCargo:66, Descripcion_esp:'Asistente de Mantenimiento', Descripcion_eng: 'Maintenance Assistant'},
    {IdCargo:67, Descripcion_esp:'Asistente de Marketing', Descripcion_eng: 'Marketing Assistant'},
    {IdCargo:68, Descripcion_esp:'Asistente de Marketing Directo y Eventos', Descripcion_eng: 'Assistant Direct Marketing and Events'},
    {IdCargo:69, Descripcion_esp:'Asistente de Operaciones', Descripcion_eng: 'Operations Assistant'},
    {IdCargo:70, Descripcion_esp:'Asistente de Planta', Descripcion_eng: 'Plant Assistant'},
    {IdCargo:71, Descripcion_esp:'Asistente de Producción', Descripcion_eng: 'Production Assistant'},
    {IdCargo:72, Descripcion_esp:'Asistente de Ventas', Descripcion_eng: 'Sales Assistant'},
    {IdCargo:73, Descripcion_esp:'Asistente de Vestuario', Descripcion_eng: 'Assistant costume designer'},
    {IdCargo:74, Descripcion_esp:'Asistente Feria Internacionales', Descripcion_eng: 'Assistant International Fairs'},
    {IdCargo:75, Descripcion_esp:'Asistente Financiero', Descripcion_eng: 'Finance Assistant'},
    {IdCargo:76, Descripcion_esp:'Asistente Museográfico', Descripcion_eng: 'Museographic Assistant'},
    {IdCargo:77, Descripcion_esp:'Asistente Social', Descripcion_eng: 'Social Worker'},
    {IdCargo:78, Descripcion_esp:'Asistente Técnico', Descripcion_eng: 'Technical Assistant'},
    {IdCargo:79, Descripcion_esp:'Asistente UDP', Descripcion_eng: 'UDP Assistant'},
    {IdCargo:80, Descripcion_esp:'Asuntos Comerciales', Descripcion_eng: 'Commercial Affairs'},
    {IdCargo:81, Descripcion_esp:'Auditor de Calidad', Descripcion_eng: 'Quality Auditor'},
    {IdCargo:82, Descripcion_esp:'Auditor de Procesos', Descripcion_eng: 'Process Auditor'},
    {IdCargo:83, Descripcion_esp:'Auditor Interno', Descripcion_eng: 'Internal Auditor'},
    {IdCargo:84, Descripcion_esp:'Auspicios', Descripcion_eng: 'Auspices'},
    {IdCargo:85, Descripcion_esp:'Auxiliar de Trade Marketing', Descripcion_eng: 'Trade Marketing Assistant'},
    {IdCargo:86, Descripcion_esp:'Bordados', Descripcion_eng: 'Embroidery'},
    {IdCargo:87, Descripcion_esp:'Catedrático', Descripcion_eng: 'Professor'},
    {IdCargo:88, Descripcion_esp:'CEO', Descripcion_eng: 'CEO'},
    {IdCargo:89, Descripcion_esp:'Certificaciones e Industria', Descripcion_eng: 'Certifications and Industry'},
    {IdCargo:90, Descripcion_esp:'Cite Laboratorio', Descripcion_eng: 'Cite Laboratory'},
    {IdCargo:91, Descripcion_esp:'Comercialización', Descripcion_eng: 'Commercialization'},
    {IdCargo:92, Descripcion_esp:'Comercio Exterior', Descripcion_eng: 'Foreing Trade'},
    {IdCargo:93, Descripcion_esp:'Comunicación Social', Descripcion_eng: 'Social Comunication'},
    {IdCargo:94, Descripcion_esp:'Comunicaciones y Asuntos Públicos', Descripcion_eng: 'Communications and Public Affairs'},
    {IdCargo:95, Descripcion_esp:'Confeccionista', Descripcion_eng: 'Confeccionista'},
    {IdCargo:96, Descripcion_esp:'Consejero Comercial', Descripcion_eng: 'Business Consultant'},
    {IdCargo:97, Descripcion_esp:'Conservadora de Arte', Descripcion_eng: 'Conservative Art'},
    {IdCargo:98, Descripcion_esp:'Consultor', Descripcion_eng: 'Consultant'},
    {IdCargo:99, Descripcion_esp:'Consultor de Comercio', Descripcion_eng: 'Business Consultant'},
    {IdCargo:100, Descripcion_esp:'Consultor Técnico', Descripcion_eng: 'Technical Consultant'},
    {IdCargo:101, Descripcion_esp:'Contador', Descripcion_eng: 'Accountant'},
    {IdCargo:102, Descripcion_esp:'Contador Apoderado', Descripcion_eng: 'Accountant and Legal Representative'},
    {IdCargo:103, Descripcion_esp:'Contralor', Descripcion_eng: 'Comptroller'},
    {IdCargo:104, Descripcion_esp:'Control de Calidad', Descripcion_eng: 'Quality Control'},
    {IdCargo:105, Descripcion_esp:'Controller Central', Descripcion_eng: 'Central Controller'},
    {IdCargo:106, Descripcion_esp:'Coordinador Académico', Descripcion_eng: 'Academic Coordinator'},
    {IdCargo:107, Descripcion_esp:'Coordinador Administrativo', Descripcion_eng: 'Administrative Coordinator'},
    {IdCargo:108, Descripcion_esp:'Coordinador Comercial', Descripcion_eng: 'Commercial Coordinator'},
    {IdCargo:109, Descripcion_esp:'Coordinador de Auspicios', Descripcion_eng: 'Sponsorship Coordinator'},
    {IdCargo:110, Descripcion_esp:'Coordinador de Comunicaciones', Descripcion_eng: 'Communications coordinator'},
    {IdCargo:111, Descripcion_esp:'Coordinador de Feria', Descripcion_eng: 'Fair Coordinator'},
    {IdCargo:112, Descripcion_esp:'Coordinador de Logística', Descripcion_eng: 'Logistics Coordinator'},
    {IdCargo:113, Descripcion_esp:'Coordinador de Mantenimiento', Descripcion_eng: 'Maintenance Coordinator'},
    {IdCargo:114, Descripcion_esp:'Coordinador de Marketing', Descripcion_eng: 'Marketing Coordinator'},
    {IdCargo:115, Descripcion_esp:'Coordinador de Marketing Internacional', Descripcion_eng: 'International Marketing Coordinator'},
    {IdCargo:116, Descripcion_esp:'Coordinador de Mercadeo', Descripcion_eng: 'Marketing Coordinator'},
    {IdCargo:117, Descripcion_esp:'Coordinador de Nuevos Negocios', Descripcion_eng: 'New Business Coordinator'},
    {IdCargo:118, Descripcion_esp:'Coordinador de Operaciones', Descripcion_eng: 'Operations coordinator'},
    {IdCargo:119, Descripcion_esp:'Coordinador de Producción', Descripcion_eng: 'Production Coordinator'},
    {IdCargo:120, Descripcion_esp:'Coordinador de Promoción Artesanal', Descripcion_eng: 'Craft Promotion Coordinator'},
    {IdCargo:121, Descripcion_esp:'Coordinador de Proyectos', Descripcion_eng: 'Project Coordinator'},
    {IdCargo:122, Descripcion_esp:'Coordinador de Seguridad', Descripcion_eng: 'Security Coordinator'},
    {IdCargo:123, Descripcion_esp:'Coordinador de Trade Marketing', Descripcion_eng: 'Trade Marketing Coordinator'},
    {IdCargo:124, Descripcion_esp:'Coordinador de Ventas', Descripcion_eng: 'Seales Coordinator'},
    {IdCargo:125, Descripcion_esp:'Coordinador General', Descripcion_eng: 'General Coordinator'},
    {IdCargo:126, Descripcion_esp:'Coordinador Ingeniería Industrial', Descripcion_eng: 'Industrial Engineering Coordinator'},
    {IdCargo:127, Descripcion_esp:'Coordinador Negocios Textil', Descripcion_eng: 'Textile Business Coordinator'},
    {IdCargo:128, Descripcion_esp:'Coordinador País', Descripcion_eng: 'Country coordinator'},
    {IdCargo:129, Descripcion_esp:'Coordinador Programa VES Exporta', Descripcion_eng: 'Program Coordinator VES Export'},
    {IdCargo:130, Descripcion_esp:'Coordinador Regional', Descripcion_eng: 'Regional Coordinator'},
    {IdCargo:131, Descripcion_esp:'Coordinadora Académica', Descripcion_eng: 'Academic Coordinator'},
    {IdCargo:132, Descripcion_esp:'Coordinadora de Diseño', Descripcion_eng: 'Design Coordinator'},
    {IdCargo:133, Descripcion_esp:'Coordinadora de Relaciones Públicas', Descripcion_eng: 'Public Relations Coordinator'},
    {IdCargo:134, Descripcion_esp:'Créditos y Cobranzas', Descripcion_eng: 'Credits and Collections'},
    {IdCargo:135, Descripcion_esp:'Decano', Descripcion_eng: 'Dean'},
    {IdCargo:136, Descripcion_esp:'Decano Facultad de Ingeniería', Descripcion_eng: 'Dean Faculty of Engineering'},
    {IdCargo:137, Descripcion_esp:'Departamento Comercial', Descripcion_eng: 'Commercial department'},
    {IdCargo:138, Descripcion_esp:'Departamento de Ventas', Descripcion_eng: 'Sales Department'},
    {IdCargo:139, Descripcion_esp:'Departamento Técnico - División Plàstico', Descripcion_eng: 'Technical Department - Plastic Division'},
    {IdCargo:140, Descripcion_esp:'Desarrollo de Productos', Descripcion_eng: 'Product Development'},
    {IdCargo:141, Descripcion_esp:'Desarrollo Textil', Descripcion_eng: 'Textile Development'},
    {IdCargo:142, Descripcion_esp:'Difusión', Descripcion_eng: 'Diffusion'},
    {IdCargo:143, Descripcion_esp:'Director', Descripcion_eng: 'Director'},
    {IdCargo:144, Descripcion_esp:'Director Académico', Descripcion_eng: 'Academic Director'},
    {IdCargo:145, Descripcion_esp:'Director Adjunto', Descripcion_eng: 'Deputy Director'},
    {IdCargo:146, Descripcion_esp:'Director Administrativo', Descripcion_eng: 'Administrative Director'},
    {IdCargo:147, Descripcion_esp:'Director Apoderado', Descripcion_eng: 'Director and Legal Representative'},
    {IdCargo:148, Descripcion_esp:'Director Centro de Capacitación', Descripcion_eng: 'Director Training Center'},
    {IdCargo:149, Descripcion_esp:'Director Comercial', Descripcion_eng: 'Commercial Director'},
    {IdCargo:150, Descripcion_esp:'Director Corporativo de Relaciones Institucionales', Descripcion_eng: 'Organizational Relations Corporate'},
    {IdCargo:151, Descripcion_esp:'Director Creativo', Descripcion_eng: 'Creative Director'},
    {IdCargo:152, Descripcion_esp:'Director Cultural', Descripcion_eng: 'Culture Director'},
    {IdCargo:153, Descripcion_esp:'Director de Administración y Finanzas', Descripcion_eng: 'Director of Administration and Finance'},
    {IdCargo:154, Descripcion_esp:'Director de Agronegocios', Descripcion_eng: 'Agribusiness Director'},
    {IdCargo:155, Descripcion_esp:'Director de Arte', Descripcion_eng: 'Art Director'},
    {IdCargo:156, Descripcion_esp:'Director de Calidad', Descripcion_eng: 'Director of Quality'},
    {IdCargo:157, Descripcion_esp:'Director de Certificación', Descripcion_eng: 'Certification Director'},
    {IdCargo:158, Descripcion_esp:'Director de Desarrollo Económico Social', Descripcion_eng: 'Social Economic Development Director'},
    {IdCargo:159, Descripcion_esp:'Director de Estudios', Descripcion_eng: 'Teaching Director'},
    {IdCargo:160, Descripcion_esp:'Director de Exportaciones', Descripcion_eng: 'Export Manager'},
    {IdCargo:161, Descripcion_esp:'Director de Geología Ambiental', Descripcion_eng: 'Director of Environmental Geology'},
    {IdCargo:162, Descripcion_esp:'Director de Geología Economica Prospección Minera', Descripcion_eng: 'Director of Economic Geology'},
    {IdCargo:163, Descripcion_esp:'Director de Geología Regional', Descripcion_eng: 'Director of Regional Geology'},
    {IdCargo:164, Descripcion_esp:'Director de Gestion de Calidad', Descripcion_eng: 'Director of Quality Management'},
    {IdCargo:165, Descripcion_esp:'Director de Gestión Integral', Descripcion_eng: 'Integral Management Director'},
    {IdCargo:166, Descripcion_esp:'Director de Implementación', Descripcion_eng: 'Implementation manager'},
    {IdCargo:167, Descripcion_esp:'Director de Investigación y Tecnología', Descripcion_eng: 'Research and Technology Director'},
    {IdCargo:168, Descripcion_esp:'Director de la Oficina Comercial', Descripcion_eng: 'Office Commercial Director'},
    {IdCargo:169, Descripcion_esp:'Director de Laboratorio', Descripcion_eng: 'Laboratory Director'},
    {IdCargo:170, Descripcion_esp:'Director de Manufactura', Descripcion_eng: 'Manufacturing Director'},
    {IdCargo:171, Descripcion_esp:'Director de Marketing', Descripcion_eng: 'Marketig Director'},
    {IdCargo:172, Descripcion_esp:'Director de Marketing y Ventas', Descripcion_eng: 'Marketing and Sales Director'},
    {IdCargo:173, Descripcion_esp:'Director de Marketing, Ventas y Operaciones', Descripcion_eng: 'Marketing, Sales and Operations Diretor'},
    {IdCargo:174, Descripcion_esp:'Director de Operaciones', Descripcion_eng: 'Operations Director'},
    {IdCargo:175, Descripcion_esp:'Director de Patrimonio Inmaterial', Descripcion_eng: 'Director of Intangible Heritage'},
    {IdCargo:176, Descripcion_esp:'Director de Producción', Descripcion_eng: 'Production Manager'},
    {IdCargo:177, Descripcion_esp:'Director de Promoción Comercial e Industrial', Descripcion_eng: 'Commercial and Industrial Promotion Directo'},
    {IdCargo:178, Descripcion_esp:'Director de Promoción de Exportaciones', Descripcion_eng: 'Export Promotion Director'},
    {IdCargo:179, Descripcion_esp:'Director de Recursos Humanos', Descripcion_eng: 'Human Resources Director'},
    {IdCargo:180, Descripcion_esp:'Director de Sistemas de Información', Descripcion_eng: 'Director of Information Systems'},
    {IdCargo:181, Descripcion_esp:'Director de Ventas', Descripcion_eng: 'Director of Sales'},
    {IdCargo:182, Descripcion_esp:'Director de Ventas Nacionales', Descripcion_eng: 'Domestic Sales Director'},
    {IdCargo:183, Descripcion_esp:'Director Defensa Institucional', Descripcion_eng: 'Institutional Defense Director'},
    {IdCargo:184, Descripcion_esp:'Director División Logística Interior', Descripcion_eng: 'Director of Internal Logistics Division'},
    {IdCargo:185, Descripcion_esp:'Director Económico', Descripcion_eng: 'Economy Director'},
    {IdCargo:186, Descripcion_esp:'Director Ejecutivo', Descripcion_eng: 'Executive Director'},
    {IdCargo:187, Descripcion_esp:'Director Ejecutivo de Eventos', Descripcion_eng: 'Executive Director of Events'},
    {IdCargo:188, Descripcion_esp:'Director Ejecutivo de Ventas', Descripcion_eng: 'Executive Director of Sales'},
    {IdCargo:189, Descripcion_esp:'Director Emérito', Descripcion_eng: 'Director Emeritus'},
    {IdCargo:190, Descripcion_esp:'Director Escuela de Ingenieria', Descripcion_eng: 'Director School of Engineering'},
    {IdCargo:191, Descripcion_esp:'Director Financiero', Descripcion_eng: 'Finance Director'},
    {IdCargo:192, Descripcion_esp:'Director General', Descripcion_eng: 'General Director'},
    {IdCargo:193, Descripcion_esp:'Director General de Industria', Descripcion_eng: 'Industry General Director'},
    {IdCargo:194, Descripcion_esp:'Director General de Marketing', Descripcion_eng: 'Marketing General Director'},
    {IdCargo:195, Descripcion_esp:'Director General Desarrollo Productivo', Descripcion_eng: 'Productive Development Director'},
    {IdCargo:196, Descripcion_esp:'Director Gerente', Descripcion_eng: 'Managing Director'},
    {IdCargo:197, Descripcion_esp:'Director Gerente Administrativo', Descripcion_eng: 'Adminstrative Managing Director'},
    {IdCargo:198, Descripcion_esp:'Director Gerente Central', Descripcion_eng: 'Central Managing Director'},
    {IdCargo:199, Descripcion_esp:'Director Gerente Comercial', Descripcion_eng: 'Commercial Managing Director'},
    {IdCargo:200, Descripcion_esp:'Director Gerente de Producción', Descripcion_eng: 'Production Managing Director'},
    {IdCargo:201, Descripcion_esp:'Director Gerente Financiero', Descripcion_eng: 'Finance Managing Director'},
    {IdCargo:202, Descripcion_esp:'Director Gerente General', Descripcion_eng: 'General Managing Director'},
    {IdCargo:203, Descripcion_esp:'Director Gerente Industrial', Descripcion_eng: 'Industrial Managing Director'},
    {IdCargo:204, Descripcion_esp:'Director Industrial', Descripcion_eng: 'Industrial Director'},
    {IdCargo:205, Descripcion_esp:'Director Instituto Opinión Pública', Descripcion_eng: 'Director Public Opinion Institute'},
    {IdCargo:206, Descripcion_esp:'Director Internacional', Descripcion_eng: 'International Director'},
    {IdCargo:207, Descripcion_esp:'Director Jurídico', Descripcion_eng: 'Legal Director'},
    {IdCargo:208, Descripcion_esp:'Director Logístico', Descripcion_eng: 'Logistics Director'},
    {IdCargo:209, Descripcion_esp:'Director Mercadeo', Descripcion_eng: 'Marketing Director'},
    {IdCargo:210, Descripcion_esp:'Director Nacional', Descripcion_eng: 'National Director'},
    {IdCargo:211, Descripcion_esp:'Director Periodístico', Descripcion_eng: 'Press Director'},
    {IdCargo:212, Descripcion_esp:'Director Regional', Descripcion_eng: 'Regional Director'},
    {IdCargo:213, Descripcion_esp:'Director Sub-Gerente General', Descripcion_eng: 'Assitant Managing Director'},
    {IdCargo:214, Descripcion_esp:'Director Técnico', Descripcion_eng: 'Technical Director'},
    {IdCargo:215, Descripcion_esp:'Director Técnico y Ventas', Descripcion_eng: 'Technicañ and Sales Director'},
    {IdCargo:216, Descripcion_esp:'Director(a) Escuela de Diseño', Descripcion_eng: 'Director School of Design'},
    {IdCargo:217, Descripcion_esp:'Director(a) Escuela de Negocios', Descripcion_eng: 'Director School of Business'},
    {IdCargo:218, Descripcion_esp:'Diseñador de Modas', Descripcion_eng: 'Fashion designer'},
    {IdCargo:219, Descripcion_esp:'Diseñador Gráfico', Descripcion_eng: 'Graphic Designer'},
    {IdCargo:220, Descripcion_esp:'Diseñador Textil', Descripcion_eng: 'Designer Clothing'},
    {IdCargo:221, Descripcion_esp:'Diseñadora de Modas', Descripcion_eng: 'Fashion designer'},
    {IdCargo:222, Descripcion_esp:'Diseñadora Gráfica', Descripcion_eng: 'Graphic Designer'},
    {IdCargo:223, Descripcion_esp:'Diseño y Producción', Descripcion_eng: 'Design and Production'},
    {IdCargo:224, Descripcion_esp:'División Artesanías', Descripcion_eng: 'Crafts Division'},
    {IdCargo:225, Descripcion_esp:'División Maquinaria ', Descripcion_eng: 'Machinery Division'},
    {IdCargo:226, Descripcion_esp:'División Plásticos', Descripcion_eng: 'Plastics Division'},
    {IdCargo:227, Descripcion_esp:'División Textil', Descripcion_eng: 'Textile Division'},
    {IdCargo:228, Descripcion_esp:'Docente', Descripcion_eng: 'Teacher'},
    {IdCargo:229, Descripcion_esp:'Economía', Descripcion_eng: 'Economy'},
    {IdCargo:230, Descripcion_esp:'Editor', Descripcion_eng: 'Publisher'},
    {IdCargo:231, Descripcion_esp:'Editor Gerente', Descripcion_eng: 'Manager Editor'},
    {IdCargo:232, Descripcion_esp:'Ejecutivo Comercial', Descripcion_eng: 'Commercial Executive'},
    {IdCargo:233, Descripcion_esp:'Ejecutivo de Compras', Descripcion_eng: 'Purchasing executive'},
    {IdCargo:234, Descripcion_esp:'Ejecutivo de Cuenta', Descripcion_eng: 'Account Executive'},
    {IdCargo:235, Descripcion_esp:'Ejecutivo de Ventas', Descripcion_eng: 'Sales Executive'},
    {IdCargo:236, Descripcion_esp:'Ejecutivo Sectorial', Descripcion_eng: 'Sector Executive'},
    {IdCargo:237, Descripcion_esp:'Ejecutivo Técnico Comercial', Descripcion_eng: 'Commercial Technical Executive'},
    {IdCargo:238, Descripcion_esp:'Embajador', Descripcion_eng: 'Ambassador'},
    {IdCargo:239, Descripcion_esp:'Encargado de Almacén', Descripcion_eng: 'Warehouse Manager'},
    {IdCargo:240, Descripcion_esp:'Encargado de Compras', Descripcion_eng: 'Purchasing agent'},
    {IdCargo:241, Descripcion_esp:'Encargado de Exportaciones', Descripcion_eng: 'Responsible for Exports'},
    {IdCargo:242, Descripcion_esp:'Encargado de Ferias ', Descripcion_eng: 'Party Manager'},
    {IdCargo:243, Descripcion_esp:'Encargado de Importaciones', Descripcion_eng: 'Responsible for Imports'},
    {IdCargo:244, Descripcion_esp:'Encargado de Licitaciones', Descripcion_eng: 'Responsible for Tenders'},
    {IdCargo:245, Descripcion_esp:'Encargado de Logística', Descripcion_eng: 'Logistics manager'},
    {IdCargo:246, Descripcion_esp:'Especialista de Artesanía y Confección Texti', Descripcion_eng: 'Craft Specialist Textile and Apparel'},
    {IdCargo:247, Descripcion_esp:'Especialista en auspicios', Descripcion_eng: 'Sponsorship Specialist'},
    {IdCargo:248, Descripcion_esp:'Especialista en Procesos Productivos', Descripcion_eng: 'Specialist in Productive Processes'},
    {IdCargo:249, Descripcion_esp:'Especialista Oferta Valor', Descripcion_eng: 'Specialist Offer Value'},
    {IdCargo:250, Descripcion_esp:'Especialista Textil', Descripcion_eng: 'Textile Specialer'},
    {IdCargo:251, Descripcion_esp:'Eventos', Descripcion_eng: 'Events'},
    {IdCargo:252, Descripcion_esp:'Fotógrafo', Descripcion_eng: 'Photographer'},
    {IdCargo:253, Descripcion_esp:'Funcionario', Descripcion_eng: 'Funcionary'},
    {IdCargo:254, Descripcion_esp:'Fundador', Descripcion_eng: 'Founder'},
    {IdCargo:255, Descripcion_esp:'Gerente', Descripcion_eng: 'Manager'},
    {IdCargo:256, Descripcion_esp:'Gerente Académico', Descripcion_eng: 'Academic Manager'},
    {IdCargo:257, Descripcion_esp:'Gerente Adjunto', Descripcion_eng: 'Deputy Manager'},
    {IdCargo:258, Descripcion_esp:'Gerente Administración y Finanzas', Descripcion_eng: 'Administrative and Finance Manager'},
    {IdCargo:259, Descripcion_esp:'Gerente Administración y Logística', Descripcion_eng: 'Administrative and Logistics Manager'},
    {IdCargo:260, Descripcion_esp:'Gerente Administrativo', Descripcion_eng: 'Administrative Manager'},
    {IdCargo:261, Descripcion_esp:'Gerente Agencia San Isidro', Descripcion_eng: 'San Isidro Agency Manager'},
    {IdCargo:262, Descripcion_esp:'Gerente CDI', Descripcion_eng: 'CDI Manager'},
    {IdCargo:263, Descripcion_esp:'Gerente Central', Descripcion_eng: 'Central Manager'},
    {IdCargo:264, Descripcion_esp:'Gerente Central de Administración', Descripcion_eng: 'Administrative Central Manager'},
    {IdCargo:265, Descripcion_esp:'Gerente Central de Finanzas', Descripcion_eng: 'Finance Central Manager'},
    {IdCargo:266, Descripcion_esp:'Gerente Central de Gestión', Descripcion_eng: 'Management Central Manager'},
    {IdCargo:267, Descripcion_esp:'Gerente Centro Tecnológico Textil y Confec.', Descripcion_eng: 'Manger Textile and Apparel Technology Cen'},
    {IdCargo:268, Descripcion_esp:'Gerente Comercial', Descripcion_eng: 'Commercial Manager'},
    {IdCargo:269, Descripcion_esp:'Gerente Comercial - Celuplast', Descripcion_eng: 'Commercial Manager - Celuplast'},
    {IdCargo:270, Descripcion_esp:'Gerente Comercial - Confecciones', Descripcion_eng: 'Commercial Manager - Garments'},
    {IdCargo:271, Descripcion_esp:'Gerente Comercial - Div. Consumo', Descripcion_eng: 'Commercial Manager - Consumer Div.'},
    {IdCargo:272, Descripcion_esp:'Gerente Comercial - Div. Hilados', Descripcion_eng: 'Commercial Manager - Yarn Division'},
    {IdCargo:273, Descripcion_esp:'Gerente Comercial - Div. Industria', Descripcion_eng: 'Commercial Manager - Industry Div.'},
    {IdCargo:274, Descripcion_esp:'Gerente Comercial - Div. Tejidos y Prendas', Descripcion_eng: 'Commercial Manager - Fabrics and Garments Division'},
    {IdCargo:275, Descripcion_esp:'Gerente Comercial - Rafia', Descripcion_eng: 'Commercial Manager - Rafia'},
    {IdCargo:276, Descripcion_esp:'Gerente Comercial y Operaciones', Descripcion_eng: 'Commercial and Operations Manager'},
    {IdCargo:277, Descripcion_esp:'Gerente Comité de Confecciones', Descripcion_eng: 'Managing Committee Confections'},
    {IdCargo:278, Descripcion_esp:'Gerente Consumo Masivo', Descripcion_eng: 'Mass Consumption Manager'},
    {IdCargo:279, Descripcion_esp:'Gerente Control de Calidad', Descripcion_eng: 'Quality Control Manager'},
    {IdCargo:280, Descripcion_esp:'Gerente Corporativo', Descripcion_eng: 'Corporate Manager'},
    {IdCargo:281, Descripcion_esp:'Gerente Creativa', Descripcion_eng: 'Creative Manager'},
    {IdCargo:282, Descripcion_esp:'Gerente de Administación de Activos', Descripcion_eng: 'Asset Management Manager'},
    {IdCargo:283, Descripcion_esp:'Gerente de Administración y Finanzas', Descripcion_eng: 'Administrative & Finance Manager'},
    {IdCargo:284, Descripcion_esp:'Gerente de Agencia Miraflores', Descripcion_eng: 'Agency Manager'},
    {IdCargo:285, Descripcion_esp:'Gerente de Alumbrado', Descripcion_eng: 'Lighting Manager'},
    {IdCargo:286, Descripcion_esp:'Gerente de Área', Descripcion_eng: 'Area Manager'},
    {IdCargo:287, Descripcion_esp:'Gerente de Calidad', Descripcion_eng: 'Quality Manager'},
    {IdCargo:288, Descripcion_esp:'Gerente de Calidad de Servicio', Descripcion_eng: 'Service Quality Manager'},
    {IdCargo:289, Descripcion_esp:'Gerente de Certificaciones', Descripcion_eng: 'Certifications Manager'},
    {IdCargo:290, Descripcion_esp:'Gerente de Codificación', Descripcion_eng: 'Coding Manager'},
    {IdCargo:291, Descripcion_esp:'Gerente de Combustibles', Descripcion_eng: 'Fuel Manager'},
    {IdCargo:292, Descripcion_esp:'Gerente de Comercialización', Descripcion_eng: 'Commercialization Manager'},
    {IdCargo:293, Descripcion_esp:'Gerente de Comercio Exterior', Descripcion_eng: 'Foreing Trade Manager'},
    {IdCargo:294, Descripcion_esp:'Gerente de Compras', Descripcion_eng: 'Purchasing Manager'},
    {IdCargo:295, Descripcion_esp:'Gerente de Comunicaciones', Descripcion_eng: 'Communications Manager'},
    {IdCargo:296, Descripcion_esp:'Gerente de Confecciones', Descripcion_eng: 'Clothing Manager'},
    {IdCargo:297, Descripcion_esp:'Gerente de Construcción', Descripcion_eng: 'Building Manager'},
    {IdCargo:298, Descripcion_esp:'Gerente de Contabilidad', Descripcion_eng: 'Accounting Manager'},
    {IdCargo:299, Descripcion_esp:'Gerente de Contabilidad y Finanzas', Descripcion_eng: 'Accounting and Finance Manager'},
    {IdCargo:300, Descripcion_esp:'Gerente de Control Interno', Descripcion_eng: 'Internal Control Manager'},
    {IdCargo:301, Descripcion_esp:'Gerente de Créditos', Descripcion_eng: 'Credit Manager'},
    {IdCargo:302, Descripcion_esp:'Gerente de Desarrollo', Descripcion_eng: 'Development Manager'},
    {IdCargo:303, Descripcion_esp:'Gerente de Desarrollo y Ventas', Descripcion_eng: 'Development and Sales Manager'},
    {IdCargo:304, Descripcion_esp:'Gerente de Diseño', Descripcion_eng: 'Desing Manager'},
    {IdCargo:305, Descripcion_esp:'Gerente de División', Descripcion_eng: 'Division Manager'},
    {IdCargo:306, Descripcion_esp:'Gerente de División Compresores', Descripcion_eng: 'Compressors of Division Manager'},
    {IdCargo:307, Descripcion_esp:'Gerente de División de Offset', Descripcion_eng: 'Offset Division Manager'},
    {IdCargo:308, Descripcion_esp:'Gerente de Envases y Embalaje', Descripcion_eng: 'Packaging and Packaging Manager'},
    {IdCargo:309, Descripcion_esp:'Gerente de Eventos', Descripcion_eng: 'Event Manager'},
    {IdCargo:310, Descripcion_esp:'Gerente de Exportación y Marketing', Descripcion_eng: 'Exports and Marketing Manager'},
    {IdCargo:311, Descripcion_esp:'Gerente de Exportaciones', Descripcion_eng: 'Export Manager'},
    {IdCargo:312, Descripcion_esp:'Gerente de Finanzas', Descripcion_eng: 'Finance manager'},
    {IdCargo:313, Descripcion_esp:'Gerente de Finanzas y Control', Descripcion_eng: 'Finance and Control Manager'},
    {IdCargo:314, Descripcion_esp:'Gerente de Finanzas y Planeamiento', Descripcion_eng: 'Finance and Planning Manager'},
    {IdCargo:315, Descripcion_esp:'Gerente de Gestión Corporativa', Descripcion_eng: 'Manager of Corporate Management'},
    {IdCargo:316, Descripcion_esp:'Gerente de Gestión de Calidad', Descripcion_eng: 'Quality Manager'},
    {IdCargo:317, Descripcion_esp:'Gerente de Hilados', Descripcion_eng: 'Yarn Manager'},
    {IdCargo:318, Descripcion_esp:'Gerente de Imagen', Descripcion_eng: 'Image Manager'},
    {IdCargo:319, Descripcion_esp:'Gerente de Importaciones', Descripcion_eng: 'Imports Manager'},
    {IdCargo:320, Descripcion_esp:'Gerente de Informática', Descripcion_eng: 'Computer Science Manager'},
    {IdCargo:321, Descripcion_esp:'Gerente de Infraestructura', Descripcion_eng: 'Infrastructure Manager'},
    {IdCargo:322, Descripcion_esp:'Gerente de Ingeniería', Descripcion_eng: 'Enginnering Manager'},
    {IdCargo:323, Descripcion_esp:'Gerente de Investigación y Proyectos', Descripcion_eng: 'Research and Projects Manager'},
    {IdCargo:324, Descripcion_esp:'Gerente de la División Print Production', Descripcion_eng: 'Print Production Division Manager'},
    {IdCargo:325, Descripcion_esp:'Gerente de Línea', Descripcion_eng: 'Line Manager'},
    {IdCargo:326, Descripcion_esp:'Gerente de Logística', Descripcion_eng: 'Logictics Manager'},
    {IdCargo:327, Descripcion_esp:'Gerente de Logística e Importaciones', Descripcion_eng: 'Logistics and Imports Manager'},
    {IdCargo:328, Descripcion_esp:'Gerente de Mantenimiento', Descripcion_eng: 'Maintenance Manager'},
    {IdCargo:329, Descripcion_esp:'Gerente de Manufactura', Descripcion_eng: 'Manufacturing manager'},
    {IdCargo:330, Descripcion_esp:'Gerente de Marca', Descripcion_eng: 'Brand Manager'},
    {IdCargo:331, Descripcion_esp:'Gerente de Marketing', Descripcion_eng: 'Marketing Manager'},
    {IdCargo:332, Descripcion_esp:'Gerente de Marketing de Minería', Descripcion_eng: 'Mining Marketing Manager'},
    {IdCargo:333, Descripcion_esp:'Gerente de Marketing y Finanzas', Descripcion_eng: 'Marketing and Finance Manager'},
    {IdCargo:334, Descripcion_esp:'Gerente de Marketing y Servicios', Descripcion_eng: 'Manager of Marketing and Services'},
    {IdCargo:335, Descripcion_esp:'Gerente de Marketing y Ventas', Descripcion_eng: 'Marketing and Sales Manager'},
    {IdCargo:336, Descripcion_esp:'Gerente de Mercadeo', Descripcion_eng: 'Marketing Manager'},
    {IdCargo:337, Descripcion_esp:'Gerente de Mercado Especialista', Descripcion_eng: 'Manager Market Specialist'},
    {IdCargo:338, Descripcion_esp:'Gerente de Minería', Descripcion_eng: 'Mining Manager'},
    {IdCargo:339, Descripcion_esp:'Gerente de MKTG e Inteligencia Comercial', Descripcion_eng: 'MKTG and Business Intelligence Manager'},
    {IdCargo:340, Descripcion_esp:'Gerente de Mype', Descripcion_eng: 'Mype Manager'},
    {IdCargo:341, Descripcion_esp:'Gerente de Negocios', Descripcion_eng: 'Business Manager'},
    {IdCargo:342, Descripcion_esp:'Gerente de Negocios Internacionales', Descripcion_eng: 'International Business Manager'},
    {IdCargo:343, Descripcion_esp:'Gerente de Operaciones', Descripcion_eng: 'Operations Manager'},
    {IdCargo:344, Descripcion_esp:'Gerente de Operaciones y Desarrollo', Descripcion_eng: 'Operations and Development Manager'},
    {IdCargo:345, Descripcion_esp:'Gerente de Operaciones y Sistemas', Descripcion_eng: 'Operations and Systems Manager'},
    {IdCargo:346, Descripcion_esp:'Gerente de Organización y Métodos', Descripcion_eng: 'Organization and Methods Manager'},
    {IdCargo:347, Descripcion_esp:'Gerente de Personal', Descripcion_eng: 'Personnel Manager'},
    {IdCargo:348, Descripcion_esp:'Gerente de Planeamiento', Descripcion_eng: 'Planning Manager'},
    {IdCargo:349, Descripcion_esp:'Gerente de Planificación', Descripcion_eng: 'Planning Manager'},
    {IdCargo:350, Descripcion_esp:'Gerente de Planta', Descripcion_eng: 'Plant Manager'},
    {IdCargo:351, Descripcion_esp:'Gerente de Preventa', Descripcion_eng: 'Presales Manager'},
    {IdCargo:352, Descripcion_esp:'Gerente de Procesos', Descripcion_eng: 'Process Manager'},
    {IdCargo:353, Descripcion_esp:'Gerente de Producción', Descripcion_eng: 'Production Manager'},
    {IdCargo:354, Descripcion_esp:'Gerente de Producto', Descripcion_eng: 'Product manager'},
    {IdCargo:355, Descripcion_esp:'Gerente de Promoción y Desarrollo', Descripcion_eng: 'Promotion and Development Manager'},
    {IdCargo:356, Descripcion_esp:'Gerente de Promoción y Marketing', Descripcion_eng: 'Promotion and Marketing Manager'},
    {IdCargo:357, Descripcion_esp:'Gerente de Proyectos', Descripcion_eng: 'Projects Manager'},
    {IdCargo:358, Descripcion_esp:'Gerente de Publicidad', Descripcion_eng: 'Advertising Manager'},
    {IdCargo:359, Descripcion_esp:'Gerente de Publicidad y Marketing', Descripcion_eng: 'Advertising and Marketing Manager'},
    {IdCargo:360, Descripcion_esp:'Gerente de Recursos Humanos', Descripcion_eng: 'Human Resources Manager'},
    {IdCargo:361, Descripcion_esp:'Gerente de Relaciones Humanas', Descripcion_eng: 'Human Relations Manager'},
    {IdCargo:362, Descripcion_esp:'Gerente de Relaciones Industriales', Descripcion_eng: 'Industrial Relations Manager'},
    {IdCargo:363, Descripcion_esp:'Gerente de Relaciones Internacionales', Descripcion_eng: 'International Relations Manager'},
    {IdCargo:364, Descripcion_esp:'Gerente de Relaciones Públicas', Descripcion_eng: 'Public Relations Manager'},
    {IdCargo:365, Descripcion_esp:'Gerente de Repuestos', Descripcion_eng: 'Spare Parts Manager'},
    {IdCargo:366, Descripcion_esp:'Gerente de Reventa', Descripcion_eng: 'Resale Manager'},
    {IdCargo:367, Descripcion_esp:'Gerente de Seguridad', Descripcion_eng: 'Security manager'},
    {IdCargo:368, Descripcion_esp:'Gerente de Seguridad Electrónica', Descripcion_eng: 'Electronic Security Manager'},
    {IdCargo:369, Descripcion_esp:'Gerente de Servicios', Descripcion_eng: 'Services Manager'},
    {IdCargo:370, Descripcion_esp:'Gerente de Servicios Externos', Descripcion_eng: 'External Services Manager'},
    {IdCargo:371, Descripcion_esp:'Gerente de Sistemas o T.I.', Descripcion_eng: 'Systems Manager or T.I.'},
    {IdCargo:372, Descripcion_esp:'Gerente de Software', Descripcion_eng: 'Software Manager'},
    {IdCargo:373, Descripcion_esp:'Gerente de Supervisión de Importaciones', Descripcion_eng: 'Imports Supervision Manager'},
    {IdCargo:374, Descripcion_esp:'Gerente de Tesorería', Descripcion_eng: 'Treasury of Manager'},
    {IdCargo:375, Descripcion_esp:'Gerente de TI', Descripcion_eng: 'TI Manager'},
    {IdCargo:376, Descripcion_esp:'Gerente de Unidad de Negocios', Descripcion_eng: 'Business Unit Manager'},
    {IdCargo:377, Descripcion_esp:'Gerente de Unidad de Negocios - Envasado', Descripcion_eng: 'Business Unit Manager - Packaging'},
    {IdCargo:378, Descripcion_esp:'Gerente de Ventas', Descripcion_eng: 'Sales Manager'},
    {IdCargo:379, Descripcion_esp:'Gerente de Ventas (México)', Descripcion_eng: 'Sales Manager (Mexico)'},
    {IdCargo:380, Descripcion_esp:'Gerente de Ventas (Perú)', Descripcion_eng: 'Sales Manager (Peru)'},
    {IdCargo:381, Descripcion_esp:'Gerente de Ventas BU', Descripcion_eng: 'BU Sales Manager'},
    {IdCargo:382, Descripcion_esp:'Gerente de Ventas de Producción', Descripcion_eng: 'Sales Manager Production Manager'},
    {IdCargo:383, Descripcion_esp:'Gerente de Ventas Industriales', Descripcion_eng: 'Industrial Sales Manager'},
    {IdCargo:384, Descripcion_esp:'Gerente de Ventas Internacional', Descripcion_eng: 'International Sales Manager'},
    {IdCargo:385, Descripcion_esp:'Gerente de Ventas Nacional', Descripcion_eng: 'National Sales Manager'},
    {IdCargo:386, Descripcion_esp:'Gerente de Ventas Prendas', Descripcion_eng: 'Apparel Sales Manager'},
    {IdCargo:387, Descripcion_esp:'Gerente de Ventas Regional', Descripcion_eng: 'Sales Manager Regional'},
    {IdCargo:388, Descripcion_esp:'Gerente de Ventas Telas', Descripcion_eng: 'Sales Manager Fabrics'},
    {IdCargo:389, Descripcion_esp:'Gerente de Ventas Textil, Cuero y Papel', Descripcion_eng: 'Textile, Leather and Paper Sales Manager'},
    {IdCargo:390, Descripcion_esp:'Gerente de Vestuario', Descripcion_eng: 'Clothes Manager'},
    {IdCargo:391, Descripcion_esp:'Gerente Departamento Químico', Descripcion_eng: 'Manager of Chemical Department'},
    {IdCargo:392, Descripcion_esp:'Gerente Departamento Textil', Descripcion_eng: 'Textile Department Manager'},
    {IdCargo:393, Descripcion_esp:'Gerente Desarrollo u Producto', Descripcion_eng: 'Development or Product Manager'},
    {IdCargo:394, Descripcion_esp:'Gerente División Finanzas', Descripcion_eng: 'Finance Manager'},
    {IdCargo:395, Descripcion_esp:'Gerente División Industrial', Descripcion_eng: 'Industrial Manager'},
    {IdCargo:396, Descripcion_esp:'Gerente División Plásticos', Descripcion_eng: 'PLastic Division Manager'},
    {IdCargo:397, Descripcion_esp:'Gerente División Producción Químicos', Descripcion_eng: 'Chemical Production Manager'},
    {IdCargo:398, Descripcion_esp:'Gerente División Textil', Descripcion_eng: 'Textile division manager'},
    {IdCargo:399, Descripcion_esp:'Gerente Ejecutivo', Descripcion_eng: 'Exucutive Manager'},
    {IdCargo:400, Descripcion_esp:'Gerente en Perú', Descripcion_eng: 'Manager in Peru'},
    {IdCargo:401, Descripcion_esp:'Gerente Ferias Internacionales', Descripcion_eng: 'Manager International Fairs'},
    {IdCargo:402, Descripcion_esp:'Gerente Financiero', Descripcion_eng: 'Finance Manager'},
    {IdCargo:403, Descripcion_esp:'Gerente Financiero y de Comercio Exterior', Descripcion_eng: 'Finance and Foreing Trade Manager'},
    {IdCargo:404, Descripcion_esp:'Gerente FUN', Descripcion_eng: 'FUN Manager'},
    {IdCargo:405, Descripcion_esp:'Gerente General', Descripcion_eng: 'General Manager'},
    {IdCargo:406, Descripcion_esp:'Gerente General Adjunto', Descripcion_eng: 'Deputy General Manager'},
    {IdCargo:407, Descripcion_esp:'Gerente General de Confecciones', Descripcion_eng: 'Fashions General Manager'},
    {IdCargo:408, Descripcion_esp:'Gerente General de Planta', Descripcion_eng: 'Plant General Manager'},
    {IdCargo:409, Descripcion_esp:'Gerente General de Unidad', Descripcion_eng: 'General Manager of Unit'},
    {IdCargo:410, Descripcion_esp:'Gerente Industrial', Descripcion_eng: 'Industrial Manager'},
    {IdCargo:411, Descripcion_esp:'Gerente Investigación y Desarrollo', Descripcion_eng: 'Research and Development Manager'},
    {IdCargo:412, Descripcion_esp:'Gerente Legal', Descripcion_eng: 'Legal Manager'},
    {IdCargo:413, Descripcion_esp:'Gerente para América Latina', Descripcion_eng: 'Manager for Latin America'},
    {IdCargo:414, Descripcion_esp:'Gerente Regional', Descripcion_eng: 'Regional Manager'},
    {IdCargo:415, Descripcion_esp:'Gerente Soluciones Tecnológicas', Descripcion_eng: 'Technological Solutions Manager'},
    {IdCargo:416, Descripcion_esp:'Gerente Técnico', Descripcion_eng: 'Technical Manager'},
    {IdCargo:417, Descripcion_esp:'Gerente Técnico y Comercial', Descripcion_eng: 'Technical and Commercial Manager'},
    {IdCargo:418, Descripcion_esp:'Gerente Tecnológico', Descripcion_eng: 'Technological Manager'},
    {IdCargo:419, Descripcion_esp:'Gerente Textil', Descripcion_eng: 'Textile Manager'},
    {IdCargo:420, Descripcion_esp:'Gerente Tour & Travel', Descripcion_eng: 'Tour and Travel Manager'},
    {IdCargo:421, Descripcion_esp:'Gerente U.N. Envases Pet', Descripcion_eng: 'Manager U.N. Pet packaging'},
    {IdCargo:422, Descripcion_esp:'Gerente ventas TLP', Descripcion_eng: 'TLP Sales Manager'},
    {IdCargo:423, Descripcion_esp:'Gerente Zonal', Descripcion_eng: 'Regional Manager'},
    {IdCargo:424, Descripcion_esp:'Gestión de Clientes', Descripcion_eng: 'Customer Management'},
    {IdCargo:425, Descripcion_esp:'Gestión de Mantenimiento y Confiabilidad', Descripcion_eng: 'Maintenance and Reliability Management'},
    {IdCargo:426, Descripcion_esp:'Gestor de Beneficios', Descripcion_eng: 'Benefits Manager'},
    {IdCargo:427, Descripcion_esp:'Gestor de Negocios', Descripcion_eng: 'Business Manager'},
    {IdCargo:428, Descripcion_esp:'Gobernador', Descripcion_eng: 'Governor'},
    {IdCargo:429, Descripcion_esp:'Hilados', Descripcion_eng: 'Yarn'},
    {IdCargo:430, Descripcion_esp:'Hilos de Coser', Descripcion_eng: 'Sewing Threads'},
    {IdCargo:431, Descripcion_esp:'Imagen de Marca', Descripcion_eng: 'Brand Image'},
    {IdCargo:432, Descripcion_esp:'Imagen Institucional', Descripcion_eng: 'Institutional Image'},
    {IdCargo:433, Descripcion_esp:'Importaciones', Descripcion_eng: 'Imports'},
    {IdCargo:434, Descripcion_esp:'Ingeniero de Planta', Descripcion_eng: 'Ingeniero de Planta'},
    {IdCargo:435, Descripcion_esp:'Ingeniero de Procesos', Descripcion_eng: 'Process Engineer'},
    {IdCargo:436, Descripcion_esp:'Ingeniero de Producción', Descripcion_eng: 'Production Engineer'},
    {IdCargo:437, Descripcion_esp:'Ingeniero Electrónico', Descripcion_eng: 'Electronic Engineer'},
    {IdCargo:438, Descripcion_esp:'Ingeniero Textil', Descripcion_eng: 'Textile Ingineer'},
    {IdCargo:439, Descripcion_esp:'International Relations', Descripcion_eng: 'International Relations'},
    {IdCargo:440, Descripcion_esp:'International Trafic Manager', Descripcion_eng: 'International Trafic Manager'},
    {IdCargo:441, Descripcion_esp:'Investigador de Patrimonio Inmaterial', Descripcion_eng: 'Intangible Heritage Researcher'},
    {IdCargo:442, Descripcion_esp:'Jefe', Descripcion_eng: 'Head'},
    {IdCargo:443, Descripcion_esp:'Jefe Administrativo', Descripcion_eng: 'Chief Administrative'},
    {IdCargo:444, Descripcion_esp:'Jefe Administrativo de Ventas', Descripcion_eng: 'Administrative Head of Sales'},
    {IdCargo:445, Descripcion_esp:'Jefe Administrativo Financiero', Descripcion_eng: 'Chief Finance Administrative'},
    {IdCargo:446, Descripcion_esp:'Jefe Area de Calzado', Descripcion_eng: 'Area Head Footwear'},
    {IdCargo:447, Descripcion_esp:'Jefe Aseguramiento Calidad', Descripcion_eng: 'Head of Quality Assurance'},
    {IdCargo:448, Descripcion_esp:'Jefe Comercial', Descripcion_eng: 'Head Commercial'},
    {IdCargo:449, Descripcion_esp:'Jefe de Abastecimiento', Descripcion_eng: 'Head of Supply'},
    {IdCargo:450, Descripcion_esp:'Jefe de Adquisiciones', Descripcion_eng: 'Chief Procurement'},
    {IdCargo:451, Descripcion_esp:'Jefe de Afiliaciones', Descripcion_eng: 'Chief Affiliations'},
    {IdCargo:452, Descripcion_esp:'Jefe de Almacén', Descripcion_eng: 'Warehouse Manager'},
    {IdCargo:453, Descripcion_esp:'Jefe de Almacén y Compras', Descripcion_eng: 'Head of Warehouse and Purchases'},
    {IdCargo:454, Descripcion_esp:'Jefe de Area de Punturas', Descripcion_eng: 'Area Chief Punctures'},
    {IdCargo:455, Descripcion_esp:'Jefe de Asistencia Técnica', Descripcion_eng: 'Head of Technical Assistance'},
    {IdCargo:456, Descripcion_esp:'Jefe de Auditoría Interna', Descripcion_eng: 'Head of Internal Audit'},
    {IdCargo:457, Descripcion_esp:'Jefe de Bordados', Descripcion_eng: 'Head Embroidery'},
    {IdCargo:458, Descripcion_esp:'Jefe de Calidad, Seguridad y Ambiente', Descripcion_eng: 'Head of quality,security and atmosphere'},
    {IdCargo:459, Descripcion_esp:'Jefe de Comercialización', Descripcion_eng: 'Head of Commercialization'},
    {IdCargo:460, Descripcion_esp:'Jefe de Comercialización y Marketing', Descripcion_eng: 'Head of Commercialization and Marketing'},
    {IdCargo:461, Descripcion_esp:'Jefe de Comercio Exterior', Descripcion_eng: 'Head of Foreing Trade'},
    {IdCargo:462, Descripcion_esp:'Jefe de Compras', Descripcion_eng: 'Chief Buyer'},
    {IdCargo:463, Descripcion_esp:'Jefe de Comunicación Corporativa', Descripcion_eng: 'Head of Corporate Communications'},
    {IdCargo:464, Descripcion_esp:'Jefe de Comunicaciones', Descripcion_eng: 'Head of Communications'},
    {IdCargo:465, Descripcion_esp:'Jefe de Confección', Descripcion_eng: 'Head of Fashion'},
    {IdCargo:466, Descripcion_esp:'Jefe de Contabilidad', Descripcion_eng: 'Head of Accounting'},
    {IdCargo:467, Descripcion_esp:'Jefe de Contabilidad y Finanzas', Descripcion_eng: 'Head of Accounting and Finance'},
    {IdCargo:468, Descripcion_esp:'Jefe de Control de Calidad', Descripcion_eng: 'Head of Quality Control'},
    {IdCargo:469, Descripcion_esp:'Jefe de Costos', Descripcion_eng: 'Cost Head'},
    {IdCargo:470, Descripcion_esp:'Jefe de Delegación', Descripcion_eng: 'Head of Delegation'},
    {IdCargo:471, Descripcion_esp:'Jefe de Desarrollo', Descripcion_eng: 'Development boss'},
    {IdCargo:472, Descripcion_esp:'Jefe de Desarrollo Organizacional', Descripcion_eng: 'Head of Organizational Development'},
    {IdCargo:473, Descripcion_esp:'Jefe de Diseño', Descripcion_eng: 'Head of Desing'},
    {IdCargo:474, Descripcion_esp:'Jefe de División', Descripcion_eng: 'Division Chief'},
    {IdCargo:475, Descripcion_esp:'Jefe de División de Plásticos', Descripcion_eng: 'Plastics Division Chief'},
    {IdCargo:476, Descripcion_esp:'Jefe de Estampados', Descripcion_eng: 'Head of prints'},
    {IdCargo:477, Descripcion_esp:'Jefe de Estudios Económicos', Descripcion_eng: 'Head of Economic Studies'},
    {IdCargo:478, Descripcion_esp:'Jefe de Eventos', Descripcion_eng: 'Head of Events'},
    {IdCargo:479, Descripcion_esp:'Jefe de Exportaciones', Descripcion_eng: 'Head of Exports'},
    {IdCargo:480, Descripcion_esp:'Jefe de Ferias', Descripcion_eng: 'Head of Fairs'},
    {IdCargo:481, Descripcion_esp:'Jefe de Finanzas', Descripcion_eng: 'Head of Finance'},
    {IdCargo:482, Descripcion_esp:'Jefe de Finanzas y Logística', Descripcion_eng: 'Head of Finance and Logistics'},
    {IdCargo:483, Descripcion_esp:'Jefe de Hilandería', Descripcion_eng: 'Head Spinning'},
    {IdCargo:484, Descripcion_esp:'Jefe de Importaciones', Descripcion_eng: 'Head of Imports'},
    {IdCargo:485, Descripcion_esp:'Jefe de Innovación', Descripcion_eng: 'Head of Innovation'},
    {IdCargo:486, Descripcion_esp:'Jefe de la División de Atención al Usuario', Descripcion_eng: 'Chief of User Support Area'},
    {IdCargo:487, Descripcion_esp:'Jefe de la U.F.P. - Confecciones', Descripcion_eng: 'Head of the U.F.P. - Confections'},
    {IdCargo:488, Descripcion_esp:'Jefe de Laboratorio', Descripcion_eng: 'Laboratory Head'},
    {IdCargo:489, Descripcion_esp:'Jefe de Licitaciones', Descripcion_eng: 'Head of Tenders'},
    {IdCargo:490, Descripcion_esp:'Jefe de Línea', Descripcion_eng: 'Head of Line'},
    {IdCargo:491, Descripcion_esp:'Jefe de Línea de Exploración', Descripcion_eng: 'Head of the Exploration Line'},
    {IdCargo:492, Descripcion_esp:'Jefe de Línea Textil', Descripcion_eng: 'Head of Textiles Line'},
    {IdCargo:493, Descripcion_esp:'Jefe de Logística', Descripcion_eng: 'Head of Logistics'},
    {IdCargo:494, Descripcion_esp:'Jefe de Mantenimiento', Descripcion_eng: 'Head of Matenance'},
    {IdCargo:495, Descripcion_esp:'Jefe de Marca', Descripcion_eng: 'Chief Brand'},
    {IdCargo:496, Descripcion_esp:'Jefe de Marketing', Descripcion_eng: 'Head of Marketing'},
    {IdCargo:497, Descripcion_esp:'Jefe de Medios', Descripcion_eng: 'Heat of Media'},
    {IdCargo:498, Descripcion_esp:'Jefe de Moda y Promoción', Descripcion_eng: 'Head of Fashion and Promotion'},
    {IdCargo:499, Descripcion_esp:'Jefe de Negocios', Descripcion_eng: 'Head of Business'},
    {IdCargo:500, Descripcion_esp:'Jefe de Oficina', Descripcion_eng: 'Office Manager'},
    {IdCargo:501, Descripcion_esp:'Jefe de Operaciones', Descripcion_eng: 'Head of Operations'},
    {IdCargo:502, Descripcion_esp:'Jefe de Personal', Descripcion_eng: 'Head of Personnel'},
    {IdCargo:503, Descripcion_esp:'Jefe de Planeamiento y Producción', Descripcion_eng: 'Head of planning and Production'},
    {IdCargo:504, Descripcion_esp:'Jefe de Planta', Descripcion_eng: 'Head of Plant'},
    {IdCargo:505, Descripcion_esp:'Jefe de Prensa', Descripcion_eng: 'Press Officer'},
    {IdCargo:506, Descripcion_esp:'Jefe de Producción', Descripcion_eng: 'Head of Production'},
    {IdCargo:507, Descripcion_esp:'Jefe de Producto', Descripcion_eng: 'Product Manager'},
    {IdCargo:508, Descripcion_esp:'Jefe de Proyectos', Descripcion_eng: 'Project Manager'},
    {IdCargo:509, Descripcion_esp:'Jefe de Publicidad', Descripcion_eng: 'Head of Advertising'},
    {IdCargo:510, Descripcion_esp:'Jefe de Recursos Humanos', Descripcion_eng: 'Human Resources Head'},
    {IdCargo:511, Descripcion_esp:'Jefe de Relaciones Públicas', Descripcion_eng: 'Head of Public Relations'},
    {IdCargo:512, Descripcion_esp:'Jefe de SCM', Descripcion_eng: 'SCM Chief'},
    {IdCargo:513, Descripcion_esp:'Jefe de Seguridad', Descripcion_eng: 'Security boss'},
    {IdCargo:514, Descripcion_esp:'Jefe de Servicio', Descripcion_eng: 'Head of Service'},
    {IdCargo:515, Descripcion_esp:'Jefe de Sistemas', Descripcion_eng: 'Head of Systems'},
    {IdCargo:516, Descripcion_esp:'Jefe de Sistemas Conductores  en seco', Descripcion_eng: 'Head of Dry Conductor Systems'},
    {IdCargo:517, Descripcion_esp:'Jefe de Store', Descripcion_eng: 'Store Head'},
    {IdCargo:518, Descripcion_esp:'Jefe de Tejeduría', Descripcion_eng: 'Head of Weaving'},
    {IdCargo:519, Descripcion_esp:'Jefe de Tesorería', Descripcion_eng: 'Head of Treasury'},
    {IdCargo:520, Descripcion_esp:'Jefe de Tintorería', Descripcion_eng: 'Head of Dry'},
    {IdCargo:521, Descripcion_esp:'Jefe de Trade Marketing', Descripcion_eng: 'Trade Marketing Head'},
    {IdCargo:522, Descripcion_esp:'Jefe de UDP', Descripcion_eng: 'Head of UDP'},
    {IdCargo:523, Descripcion_esp:'Jefe de Unidad de Comercio', Descripcion_eng: 'Head of Unid of Commerce'},
    {IdCargo:524, Descripcion_esp:'Jefe de Unidad de Reciclaje', Descripcion_eng: 'Recycling Unit Chief'},
    {IdCargo:525, Descripcion_esp:'Jefe de Ventas', Descripcion_eng: 'Head of Sales'},
    {IdCargo:526, Descripcion_esp:'Jefe de Ventas - División Maquinarias', Descripcion_eng: 'Head of Sales - Machinery Division'},
    {IdCargo:527, Descripcion_esp:'Jefe de Ventas - Textil', Descripcion_eng: 'Head of Sales - Textile'},
    {IdCargo:528, Descripcion_esp:'Jefe de Ventas Químicos', Descripcion_eng: 'Chemical Sales Manager'},
    {IdCargo:529, Descripcion_esp:'Jefe de Ventas y Marketing', Descripcion_eng: 'Head of Sales and Marketing'},
    {IdCargo:530, Descripcion_esp:'Jefe de Visual', Descripcion_eng: 'Head of Visual'},
    {IdCargo:531, Descripcion_esp:'Jefe del Área Químicos y Plásticos', Descripcion_eng: 'Head of the Chemical and Plastics Area'},
    {IdCargo:532, Descripcion_esp:'Jefe del Sector Comercial', Descripcion_eng: 'Head of Commercial Sector'},
    {IdCargo:533, Descripcion_esp:'Jefe Departamento Académico Comunicaci', Descripcion_eng: 'Academic Department Head'},
    {IdCargo:534, Descripcion_esp:'Jefe Departamento de Matricería', Descripcion_eng: 'Head of Matricería'},
    {IdCargo:535, Descripcion_esp:'Jefe Departamento de Químicos', Descripcion_eng: 'Chief Chemical Department'},
    {IdCargo:536, Descripcion_esp:'Jefe Departamento e Inyección', Descripcion_eng: 'Injection Department Head'},
    {IdCargo:537, Descripcion_esp:'Jefe División Textil', Descripcion_eng: 'Textile Division Chief'},
    {IdCargo:538, Descripcion_esp:'Jefe Línea Industrial', Descripcion_eng: 'Industrial Line Manager'},
    {IdCargo:539, Descripcion_esp:'Jefe Técnico', Descripcion_eng: 'Technical Chief'},
    {IdCargo:540, Descripcion_esp:'Laboratorista', Descripcion_eng: 'Laboratorista'},
    {IdCargo:541, Descripcion_esp:'Línea Farmaceútica', Descripcion_eng: 'Pharmaceutical Line'},
    {IdCargo:542, Descripcion_esp:'Linea Textil', Descripcion_eng: 'Textile Line'},
    {IdCargo:543, Descripcion_esp:'Mantenimiento Electrónico', Descripcion_eng: 'Electronic Maintenance'},
    {IdCargo:544, Descripcion_esp:'Mantenimiento y Producción', Descripcion_eng: 'Maintenance and Production'},
    {IdCargo:545, Descripcion_esp:'Maquinista', Descripcion_eng: 'Machinist'},
    {IdCargo:546, Descripcion_esp:'Marca y Publicidad', Descripcion_eng: 'Brand & Advertising'},
    {IdCargo:547, Descripcion_esp:'Marketing', Descripcion_eng: 'Marketing'},
    {IdCargo:548, Descripcion_esp:'Marketing Directo', Descripcion_eng: 'Direct Marketing'},
    {IdCargo:549, Descripcion_esp:'Marketing South América', Descripcion_eng: 'Marketing South America'},
    {IdCargo:550, Descripcion_esp:'Marketing y Publicidad', Descripcion_eng: 'Marketing and Advertising'},
    {IdCargo:551, Descripcion_esp:'Mecánico', Descripcion_eng: 'Mechanical'},
    {IdCargo:552, Descripcion_esp:'Mecánico Textil', Descripcion_eng: 'Textil mechanic'},
    {IdCargo:553, Descripcion_esp:'Mercado Externo', Descripcion_eng: 'External Market'},
    {IdCargo:554, Descripcion_esp:'Mercado Interno', Descripcion_eng: 'Internal Market'},
    {IdCargo:555, Descripcion_esp:'Ministro', Descripcion_eng: 'Minister'},
    {IdCargo:556, Descripcion_esp:'Muestrista', Descripcion_eng: 'Sampler'},
    {IdCargo:557, Descripcion_esp:'Negocios Internacionales', Descripcion_eng: 'International Business'},
    {IdCargo:558, Descripcion_esp:'No identificado', Descripcion_eng: 'Not identified'},
    {IdCargo:559, Descripcion_esp:'Nuevos Desarrollos', Descripcion_eng: 'New Developments'},
    {IdCargo:560, Descripcion_esp:'Office Manager', Descripcion_eng: 'Office Manager'},
    {IdCargo:561, Descripcion_esp:'Operaciones', Descripcion_eng: 'Operations'},
    {IdCargo:562, Descripcion_esp:'Operador Comercial', Descripcion_eng: 'Commercial Operator'},
    {IdCargo:563, Descripcion_esp:'Operario', Descripcion_eng: 'Operator'},
    {IdCargo:564, Descripcion_esp:'Organización de Ferias', Descripcion_eng: 'Trade Organization'},
    {IdCargo:565, Descripcion_esp:'Past Presidente', Descripcion_eng: 'Past President'},
    {IdCargo:566, Descripcion_esp:'Patronista', Descripcion_eng: 'Pattern Maker'},
    {IdCargo:567, Descripcion_esp:'Pigmentos y Aditivos', Descripcion_eng: 'Pigments and Additives'},
    {IdCargo:568, Descripcion_esp:'Pigmentos y Dispersantes', Descripcion_eng: 'Pigments and Dispersants'},
    {IdCargo:569, Descripcion_esp:'Presidente', Descripcion_eng: 'President'},
    {IdCargo:570, Descripcion_esp:'Presidente de la Comisión de Divulgación Profesión', Descripcion_eng: 'Chairman of the Profession Disclosure Commission'},
    {IdCargo:571, Descripcion_esp:'Presidente de la Comisión de Economía', Descripcion_eng: 'President of the Economic Commission'},
    {IdCargo:572, Descripcion_esp:'Presidente de la Comisión de Prensa y Propaganda', Descripcion_eng: 'President of the Press and Propaganda Commission'},
    {IdCargo:573, Descripcion_esp:'Presidente de la Comisión de RR.PP.', Descripcion_eng: 'President of the Public Relations Commission'},
    {IdCargo:574, Descripcion_esp:'Presidente de la Comisión Técnico Consultiv', Descripcion_eng: 'President of the Technical Advisory Committee'},
    {IdCargo:575, Descripcion_esp:'Presidente de Ventas', Descripcion_eng: 'Sales President'},
    {IdCargo:576, Descripcion_esp:'Presidente del Consejo de Administración', Descripcion_eng: 'Chairman of the Board Managers'},
    {IdCargo:577, Descripcion_esp:'Presidente del Directorio', Descripcion_eng: 'Chairman of the Board of Directors'},
    {IdCargo:578, Descripcion_esp:'Presidente Ejecutivo', Descripcion_eng: 'Executive President'},
    {IdCargo:579, Descripcion_esp:'Primer Vice Presidente', Descripcion_eng: 'First Vice President'},
    {IdCargo:580, Descripcion_esp:'Pro Secretario', Descripcion_eng: 'Pro Secretary'},
    {IdCargo:581, Descripcion_esp:'Pro Tesorero', Descripcion_eng: 'Treasurer Pro'},
    {IdCargo:582, Descripcion_esp:'Procurador', Descripcion_eng: 'Attorney'},
    {IdCargo:583, Descripcion_esp:'Producción', Descripcion_eng: 'Production'},
    {IdCargo:584, Descripcion_esp:'Programación', Descripcion_eng: 'Programming'},
    {IdCargo:585, Descripcion_esp:'Programador', Descripcion_eng: 'Programmer'},
    {IdCargo:586, Descripcion_esp:'Programador de Estampado', Descripcion_eng: 'Print Scheduler'},
    {IdCargo:587, Descripcion_esp:'Promoción Comercial', Descripcion_eng: 'Trade Promotion'},
    {IdCargo:588, Descripcion_esp:'Promoción Internacional', Descripcion_eng: 'International Promotion'},
    {IdCargo:589, Descripcion_esp:'Promotor Cultural', Descripcion_eng: 'Cultural Promoter'},
    {IdCargo:590, Descripcion_esp:'Propietario', Descripcion_eng: 'Owner'},
    {IdCargo:591, Descripcion_esp:'Pull Interno', Descripcion_eng: 'Internal Pull'},
    {IdCargo:592, Descripcion_esp:'Recepcionista', Descripcion_eng: 'Receptionist'},
    {IdCargo:593, Descripcion_esp:'Rector', Descripcion_eng: 'Chancellor'},
    {IdCargo:594, Descripcion_esp:'Relaciones Institucionales', Descripcion_eng: 'Organizational Relations'},
    {IdCargo:595, Descripcion_esp:'Relaciones Públicas', Descripcion_eng: 'Public Relations'},
    {IdCargo:596, Descripcion_esp:'Reportero', Descripcion_eng: 'Reporter'},
    {IdCargo:597, Descripcion_esp:'Representante', Descripcion_eng: 'Representative'},
    {IdCargo:598, Descripcion_esp:'Representante Comercial', Descripcion_eng: 'Trade Representative'},
    {IdCargo:599, Descripcion_esp:'Representante Comercial Plástico', Descripcion_eng: 'Plastic Commercial Representative'},
    {IdCargo:600, Descripcion_esp:'Representante de Ventas', Descripcion_eng: 'Sales Manager'},
    {IdCargo:601, Descripcion_esp:'Representante en Perú', Descripcion_eng: 'Representative in Peru'},
    {IdCargo:602, Descripcion_esp:'Representante Legal', Descripcion_eng: 'Legal Representative'},
    {IdCargo:603, Descripcion_esp:'Representante Técnico Comercial', Descripcion_eng: 'Commercial Technical Representative'},
    {IdCargo:604, Descripcion_esp:'Responsable de Laboratorio', Descripcion_eng: 'Laboratory responsible'},
    {IdCargo:605, Descripcion_esp:'Secretaria', Descripcion_eng: 'Secretary'},
    {IdCargo:606, Descripcion_esp:'Secretaria de Gerencia', Descripcion_eng: 'Management Secretary'},
    {IdCargo:607, Descripcion_esp:'Secretaria de Presidencia', Descripcion_eng: 'President Secretary'},
    {IdCargo:608, Descripcion_esp:'Secretaria de Ventas', Descripcion_eng: 'Sales Secretary'},
    {IdCargo:609, Descripcion_esp:'Secretaria Técnica', Descripcion_eng: 'Technical Secretary'},
    {IdCargo:610, Descripcion_esp:'Secretario General', Descripcion_eng: 'Secretary General'},
    {IdCargo:611, Descripcion_esp:'Sectorista', Descripcion_eng: 'Sectorist'},
    {IdCargo:612, Descripcion_esp:'Segunda Secretaria Economía', Descripcion_eng: 'Second Economy Secretary'},
    {IdCargo:613, Descripcion_esp:'Segundo Vice Presidente', Descripcion_eng: 'Second Vice President'},
    {IdCargo:614, Descripcion_esp:'Servicio al Cliente', Descripcion_eng: 'Customer service'},
    {IdCargo:615, Descripcion_esp:'Servicio de Información', Descripcion_eng: 'Information Services'},
    {IdCargo:616, Descripcion_esp:'Servicio Técnico', Descripcion_eng: 'Technical Service'},
    {IdCargo:617, Descripcion_esp:'Socio', Descripcion_eng: 'Partner'},
    {IdCargo:618, Descripcion_esp:'Sub - Gerente de Infraestructura', Descripcion_eng: 'Sub - Infrastructure Manager'},
    {IdCargo:619, Descripcion_esp:'Sub Gerente Adjunto de Leasing', Descripcion_eng: 'Deputy Assistant Manager Leasing'},
    {IdCargo:620, Descripcion_esp:'Sub Gerente Comercial', Descripcion_eng: 'Commercial Assistant Manager'},
    {IdCargo:621, Descripcion_esp:'Sub Gerente de Exportaciones', Descripcion_eng: 'Deputy Export Manager'},
    {IdCargo:622, Descripcion_esp:'Sub Gerente de Mype', Descripcion_eng: 'Mype Sub Manager'},
    {IdCargo:623, Descripcion_esp:'Sub Gerente de Publicidad', Descripcion_eng: 'Advertising Sub Manager'},
    {IdCargo:624, Descripcion_esp:'Sub Gerente División Textil', Descripcion_eng: 'Assistant Manager Textile Division'},
    {IdCargo:625, Descripcion_esp:'Sub Gerente General', Descripcion_eng: 'Deputy General Manager'},
    {IdCargo:626, Descripcion_esp:'Sub Gerente Trade Center', Descripcion_eng: 'Trade Center Sub Manager'},
    {IdCargo:627, Descripcion_esp:'Subdirectora de Mercadeo y Desarrollo', Descripcion_eng: 'Assistent Director of Marketing and Develop'},
    {IdCargo:628, Descripcion_esp:'Sub-Gerente', Descripcion_eng: 'Assistant Manager'},
    {IdCargo:629, Descripcion_esp:'Sub-Gerente Administrativo', Descripcion_eng: 'Administrative Assitant Manager'},
    {IdCargo:630, Descripcion_esp:'Sub-Gerente de Comercialización', Descripcion_eng: 'Commercialization Assistant Manager'},
    {IdCargo:631, Descripcion_esp:'Sub-Gerente de Logística', Descripcion_eng: 'Logistis Assistant Manager'},
    {IdCargo:632, Descripcion_esp:'Sub-Gerente de Marketing', Descripcion_eng: 'Marketing Assistant Manager'},
    {IdCargo:633, Descripcion_esp:'Sub-Gerente de Marketing y Ventas', Descripcion_eng: 'Marketing and Sales Assistant Manager'},
    {IdCargo:634, Descripcion_esp:'Sub-Gerente de Operaciones', Descripcion_eng: 'Operations Assintan Manager'},
    {IdCargo:635, Descripcion_esp:'Sub-Gerente de Producción', Descripcion_eng: 'Prodution Assistant Manager'},
    {IdCargo:636, Descripcion_esp:'Sub-Gerente de Ventas', Descripcion_eng: 'Sales Assistant Manager'},
    {IdCargo:637, Descripcion_esp:'Superintendente', Descripcion_eng: 'Superintendent'},
    {IdCargo:638, Descripcion_esp:'Superintendente de Planta', Descripcion_eng: 'Plant Superintendent'},
    {IdCargo:639, Descripcion_esp:'Superintendente Producción', Descripcion_eng: 'Prodution Superintendent'},
    {IdCargo:640, Descripcion_esp:'Supervisor', Descripcion_eng: 'Supervisor'},
    {IdCargo:641, Descripcion_esp:'Supervisor de Almacén', Descripcion_eng: 'Warehouse supervisor'},
    {IdCargo:642, Descripcion_esp:'Supervisor de Compras', Descripcion_eng: 'Purchasing Supervisor'},
    {IdCargo:643, Descripcion_esp:'Supervisor de Control de Inventarios', Descripcion_eng: 'Inventory Control Supervisor'},
    {IdCargo:644, Descripcion_esp:'Supervisor de Marketing', Descripcion_eng: 'Marketing Supervisor'},
    {IdCargo:645, Descripcion_esp:'Supervisor de Producción', Descripcion_eng: 'Production Supervisor'},
    {IdCargo:646, Descripcion_esp:'Supervisor de Seguridad', Descripcion_eng: 'Security Supervisor'},
    {IdCargo:647, Descripcion_esp:'Supervisor de Tejeduría', Descripcion_eng: 'Supervisor of Weaving'},
    {IdCargo:648, Descripcion_esp:'Supervisor de Ventas', Descripcion_eng: 'Sales Supervisor'},
    {IdCargo:649, Descripcion_esp:'Supervisor Dpto. Matricería', Descripcion_eng: 'Supervisor Dept. Matricería'},
    {IdCargo:650, Descripcion_esp:'Supervisor General', Descripcion_eng: 'General Supervisor'},
    {IdCargo:651, Descripcion_esp:'Técnica Consultiva', Descripcion_eng: 'Consulting Technical'},
    {IdCargo:652, Descripcion_esp:'Técnico', Descripcion_eng: 'Technical'},
    {IdCargo:653, Descripcion_esp:'Técnico Comercial', Descripcion_eng: 'Commercial Technical'},
    {IdCargo:654, Descripcion_esp:'Técnico de Laboratorio', Descripcion_eng: 'Laboratory Technician'},
    {IdCargo:655, Descripcion_esp:'Técnico de Mantenimiento', Descripcion_eng: 'Maintenance Technician'},
    {IdCargo:656, Descripcion_esp:'Tecnico de Planta', Descripcion_eng: 'Plant Technician'},
    {IdCargo:657, Descripcion_esp:'Técnico de Sistema', Descripcion_eng: 'System Technician'},
    {IdCargo:658, Descripcion_esp:'Técnico Electronico', Descripcion_eng: 'Electronic Technician'},
    {IdCargo:659, Descripcion_esp:'Tejeduría', Descripcion_eng: 'Weaving'},
    {IdCargo:660, Descripcion_esp:'Tercer Vice Presidente', Descripcion_eng: 'Thrid Vice President'},
    {IdCargo:661, Descripcion_esp:'Tesorero', Descripcion_eng: 'Treasurer'},
    {IdCargo:662, Descripcion_esp:'Titular Gerente', Descripcion_eng: 'Owner Manager'},
    {IdCargo:663, Descripcion_esp:'Ventas', Descripcion_eng: 'Sales'},
    {IdCargo:664, Descripcion_esp:'Ventas Institucionales', Descripcion_eng: 'Institutional Sales'},
    {IdCargo:665, Descripcion_esp:'Ventas Internacionales', Descripcion_eng: 'International Sales'},
    {IdCargo:666, Descripcion_esp:'Vice Ministro de Mype e Industria', Descripcion_eng: 'Mype and Industry Vice Minister'},
    {IdCargo:667, Descripcion_esp:'Vice Presidente', Descripcion_eng: 'Vice President'},
    {IdCargo:668, Descripcion_esp:'Vice Presidente de Finanzas', Descripcion_eng: 'Finance Vice President'},
    {IdCargo:669, Descripcion_esp:'Vice Presidente de Legal', Descripcion_eng: 'Legal Vice President'},
    {IdCargo:670, Descripcion_esp:'Vice Presidente de Logística', Descripcion_eng: 'Logistics Vice President'},
    {IdCargo:671, Descripcion_esp:'Vice Presidente del Consejo de Administración', Descripcion_eng: 'Board of Managers Vice President'},
    {IdCargo:672, Descripcion_esp:'Vice Presidente Desarrollo', Descripcion_eng: 'Development Vice President'},
    {IdCargo:673, Descripcion_esp:'Vice Presidente Ejecutivo', Descripcion_eng: 'Executive Vice President'},
    {IdCargo:674, Descripcion_esp:'Vice Presidente Ejecutivo Finanzas', Descripcion_eng: 'Finance Executive Vice President'},
    {IdCargo:675, Descripcion_esp:'Vice Presidente para Latinoamérica', Descripcion_eng: 'Vice President for Latin America'},
    {IdCargo:676, Descripcion_esp:'Vice Presidente Residente', Descripcion_eng: 'Resident Vice President'},
    {IdCargo:677, Descripcion_esp:'Vice Presidente UN Closures', Descripcion_eng: 'Vice President UN Closures'},
    {IdCargo:678, Descripcion_esp:'Vice Presidente UN Industrial', Descripcion_eng: 'Vice President UN Industrial'},
    {IdCargo:679, Descripcion_esp:'Vice Presidente UN Recycling', Descripcion_eng: 'Vice President UN Recycling'},
    {IdCargo:680, Descripcion_esp:'Vice Rector Académico', Descripcion_eng: 'Academic Vice Chancellor'},
    {IdCargo:681, Descripcion_esp:'Vice Rector Administrativo', Descripcion_eng: 'Administrative Vice Chancellor'},
    {IdCargo:682, Descripcion_esp:'Vicepresidente de Ventas', Descripcion_eng: 'Vice President of Sales'},
    {IdCargo:683, Descripcion_esp:'Vicepresidente Servicios Industriales', Descripcion_eng: 'Vice President Industrial Services'}
]